# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React App Build and Push

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - .README.md
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - name: Restore node_modules from cache
      uses: actions/cache@v3
      with:
       path: |
         node_modules
         */*/node_modules
       key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    # - name: Production build
    - uses: actions/checkout@v3
    - name: Production build
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        #${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
        
   #  - name : Build React app
   # # - run: npm ci
   #    run: npm ci && npm run build --if-present
   #  #- run: npm run deploy

    - name: Deploy to gh-pages
      run: |
       git config --global user.name $user_name
       git config --global user.email $user_email
       git remote set-url origin https://${github_token}@github.com/${repository}
       npm run deploy
      env:
       user_name: 'github-actions[bot]'
       user_email: 'github-actions[bot]@users.noreply.github.com'
       github_token: ${{ secrets.PAGES_TOKEN }}
       repository: ${{ github.repository }}
